### ISSUE TITLE
CVCalendar Changes

### ISSUE THREAD

**Issue by Mozharovsky** [Mozharovsky/CVCalendar#222]
> This issue is a work in progress. Links and more info will be added soon. 

## Summary
As we started working on version **2.0.0** we want to announce changes we're going to make, so we can start a discussion where any interested developer could ask a question regarding a new version or a new API or suggest a new feature and/or change. 

Also if you want to ask us a direct question, API developers are listed below. 

## Developers
@Mozharovsky
@elsesiy 

#### New features 
- [ ] Year mode 
- [ ] Month flow mode 
- [ ] Animations for mode changes
- [ ] Autolayout support for basic units (day, week and month views) 
- [ ] Exhaustive documentation on methods & properties 
- [ ] IBDesignable interface support for Appearance properties 
- [ ] Appearance interface for CVCalendarView (instead of using a custom protocol) **[Under discussion]**

#### Enhancements
> Issues have been opened since #28 

- [ ] Date range selection #12 
- [ ] Multiple dates selection #32 
- [ ] Day views interaction disable #20  
- [ ] Change rotation mode (re-render) **[Might be unnecessary due to AutoLayout]**
- [ ] Custom markers & labels' positioning #49
- [ ] Min/Max month view for load
- [ ] Cache scrolling #55 
- [ ] Views reuse 

## Bug fixes

> TODO: @elsesiy: Please try to collect the most serious bugs to be fixed into a list here.
