### ISSUE TITLE
CVCalendar-Release [1.1.0]

### ISSUE THREAD

**Issue by Mozharovsky** [Mozharovsky/CVCalendar#28]
## Enhancements
- [ ] Date range selection #12 
- [ ] Multiple dates selection #32 
- [x] Transition animation between modes (week-month) #17 
- [ ] Day views interaction disable #20 
- [ ] Multiple dots for day views #27 
- [ ] Personal background color for every day view #27 
- [ ] Update dot markers (e.g. if some day views shouldn't have ones anymore) #27 
- [ ] Change rotation mode (re-render)
- [x] Localization 
- [x] Custom fonts for both menu and dates' labels 
- [ ] Custom AuxiliaryView background image #49
- [ ] Min/Max month view for load
- [x] Dynamic content size (week and day views)
- [ ] Cache scrolling #55 
- [ ] Supplementary views for day views #61 
- [ ] Views reuse 

## Major bug fixes 

- [x] Committing frames' update only once #18 #22 #31
- [x] CVDate math for days out #23 
- [x] Toggling to current day view if it isn't selected #30 
- [x] Unmanaged dragging of content view (scroll area)
- [x] Top marker glitch on first load 
- [x] Glitch on chaotic scroll 
- [x] Delay on appearing (make a lazy init on content view)
- [x] Major optimisation (retain cycle issue between views)
- [x] Delegate notification on toggling or month change 
- [x] Interaction with invisible day views
- [x] Double first day in month selection
- [x] MonthContentViewController optimization
- [x] WeekContentViewController optimization 
- [ ] iOS 7 <-> iOS 8 bridging #50 

## Documentation 

- [ ] Update documentation (better struct, usage section)
- [ ] Write an article on using CVCalendar with all features 
- [ ] Record a video in a couple with the article

**Comment by martjemeyer** [comment]
:+1:

**Comment by Mozharovsky** [comment]
Hardly do I realise how such a big release can be associated with a minor version. 
This release is 1.1.0 version. So changes are coming.

**Comment by nopptr** [comment]
To create Events into the calendar 
usr to method

thank you

**Comment by elsesiy** [comment]
@nopptr Please elaborate on what do you need. I don't get it..

**Comment by nopptr** [comment]
I want to add actively show in calendar

I'm sorry if I'm wrong, I'm not good at English.

Thank
Noppadorn

**Comment by elsesiy** [comment]
@nopptr I'm sorry I still don't understand.

**Comment by shrikantwalekar-tudip** [comment]
Hi, I Iove this beautiful library.
I want to know- can we highlight some dates we want? with circular colour in background or any else way
If yes, how to do it, I am new in swift coding.

**Comment by AB91189** [comment]
Hi @elsesiy ,

I am using week view, but to fetch the current month i am using the same instance as in Month view

calendarViewWeek!.presentedDate.month

But presentedDate is nil Week view case but not in Month view. Not able to understand why????


Thanks
Abhishek

**Comment by varunchanni** [comment]
Have you given any thought to add support for drag and drop for events in week view?
